name: blog
type: python:3.12

relationships:
  database: "database:postgresql"

# You do not need the `database` section here anymore

web:
    upstream:
        socket_family: unix
    commands:
        start: 'gunicorn -w 4 -b unix:$SOCKET blog.wsgi:application'
    locations:
      '/':
          passthru: true
      '/static':
          root: 'static'
          expires: 1h
          allow: true

disk: 512

mounts:
    'logs':
        source: local
        source_path: logs

dependencies:
  python3:
    pip: "23.3.1"

hooks:
    build: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt

        mkdir logs
        python manage.py collectstatic
        rm -rf logs
    deploy: |
        python manage.py migrate
