# Generated by Django 5.2 on 2025-05-06 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_individaul_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individaul',
            name='esm',
        ),
        migrations.RemoveField(
            model_name='individaul',
            name='name',
        ),
        migrations.AddField(
            model_name='individaul',
            name='names',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('esm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.overall')),
            ],
        ),
    ]
