# Generated by Django 5.2 on 2025-05-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_individaul_esm_remove_individaul_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explain2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('esm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.individaul')),
            ],
        ),
    ]
