# Generated by Django 5.2 on 2025-05-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_explain2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explain',
            old_name='esm',
            new_name='overal',
        ),
    ]
