# Generated by Django 5.2 on 2025-05-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_esm_explain_overal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explain',
            old_name='overal',
            new_name='esm',
        ),
    ]
