# Generated by Django 5.2 on 2025-05-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_explain_owner_explain2_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explain',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.RenameField(
            model_name='individaul',
            old_name='names',
            new_name='name',
        ),
    ]
