# Generated by Django 5.2 on 2025-05-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_explain_options_rename_names_individaul_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explain2',
            old_name='esm',
            new_name='esmm',
        ),
    ]
